package com.meiya.whalex.jdbc.parser;

import cn.hutool.core.collection.CollectionUtil;
import com.meiya.whalex.db.builder.TableConfigurationBuilder;
import com.meiya.whalex.db.entity.AddParamCondition;
import com.meiya.whalex.db.entity.DatabaseSetting;
import com.meiya.whalex.db.entity.PageResult;
import com.meiya.whalex.db.entity.TableSetting;
import com.meiya.whalex.db.entity.UpsertParamBatchCondition;
import com.meiya.whalex.db.entity.UpsertParamCondition;
import com.meiya.whalex.db.module.DbModuleService;
import com.meiya.whalex.jdbc.DatResultSet;
import com.meiya.whalex.sql.module.RdbmsModuleService;
import com.meiya.whalex.sql2dsl.parser.InsertSqlToDslParser;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * 新增数据sql解析
 *
 * @author 蔡荣桂
 * @date 2022/06/27
 * @project whalex-dat-sql
 */
public class InsertSqlParser implements ISqlParser<Integer>, ISqlParserWithGeneratedKeys<Integer> {

    private String tableName;

    DbModuleService service;

    DatabaseSetting databaseSetting;

    private String sql;

    private Object[] params;

    private int autoGeneratedKeys;

    private String[] columnNames;

    private ResultSet resultSet;


    public InsertSqlParser(String sql, Object[] params, DbModuleService service, DatabaseSetting databaseSetting) {
        this.sql = sql;
        this.params = params;
        this.service = service;
        this.databaseSetting = databaseSetting;
    }

    @Override
    public Integer execute() throws Exception {
        PageResult pageResult = executeAndGetPageResult();
        return (int) pageResult.getTotal();
    }

    @Override
    public PageResult executeAndGetPageResult() throws Exception {
        InsertSqlToDslParser parser = new InsertSqlToDslParser(sql, params);
        parser.setAutoGeneratedKeys(autoGeneratedKeys);
        parser.setColumnNames(columnNames);
        Object result = parser.handle();

        //获取表名
        tableName = parser.getTableName();

        // 使用复杂sql能力，不需要解析
        if (result == null) {
            if (!(service instanceof RdbmsModuleService)) {
                throw new RuntimeException("insert into table(column) select 格式的sql,只支持关系型数据库");
            }

            return executeBySql();
        }

        //新增
        if (result instanceof AddParamCondition) {
            return executeInsert((AddParamCondition) result);
        }

        TableSetting tableSetting = TableConfigurationBuilder.builder().tableName(tableName).build();

        //更新或新增
        if (result instanceof UpsertParamCondition) {
            PageResult pageResult = service.saveOrUpdate(databaseSetting, tableSetting, (UpsertParamCondition) result);
            return pageResult;
        }

        //批量更新或新增
        PageResult pageResult = service.saveOrUpdateBatch(databaseSetting, tableSetting, (UpsertParamBatchCondition) result);
        return pageResult;
    }

    private PageResult executeBySql() throws Exception {
        RdbmsModuleService rdbmsModuleService = (RdbmsModuleService) service;

        List<Object> paramList = new ArrayList<>();
        if (params != null) {
            paramList.addAll(Arrays.asList(params));
        }

        PageResult pageResult = rdbmsModuleService.updateBySql(databaseSetting, sql, paramList);
        return pageResult;
    }

    private PageResult executeInsert(AddParamCondition addParamCondition) throws Exception {


        TableSetting tableSetting = TableConfigurationBuilder.builder().tableName(tableName).build();

        PageResult pageResult = service.insert(databaseSetting, tableSetting, addParamCondition);

        //数据返回
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS || columnNames != null) {

            List<Map> rows = pageResult.getRows();
            if (CollectionUtil.isNotEmpty(rows)) {

                List<String> schema = new ArrayList<>();

                Set<String> keySet = rows.get(0).keySet();
                schema.addAll(keySet);

                resultSet = new DatResultSet(rows, schema);

            } else {
                resultSet = new DatResultSet();
            }

        }

        return pageResult;

    }

    @Override
    public ResultSet getGeneratedKeys() {
        return resultSet;
    }

    @Override
    public void setAutoGeneratedKeys(int autoGeneratedKeys) {
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    @Override
    public void setColumnNames(String[] columnNames) {
        this.columnNames = columnNames;
    }
}
