package com.meiya.whalex.jdbc.parser;


import java.sql.ResultSet;

/**
 * sql解析
 * 插入sql具有返回主键的能力
 * @author 蔡荣桂
 * @date 2022/07/08
 * @project whalex-dat-sql
 */
public interface ISqlParserWithGeneratedKeys<T> extends ISqlParser<T>{


    ResultSet getGeneratedKeys();

    void setAutoGeneratedKeys(int autoGeneratedKeys);

    void setColumnNames(String[] columnNames);
}
