package com.meiya.whalex.jdbc;

import com.meiya.whalex.db.entity.DatabaseSetting;
import com.meiya.whalex.db.entity.ani.AniBinaryStreamParameter;
import com.meiya.whalex.db.template.BaseDbConfTemplate;
import com.meiya.whalex.interior.db.constant.DbResourceEnum;
import lombok.extern.slf4j.Slf4j;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;


/**
 * dat预处理statement对象
 *
 * @author 蔡荣桂
 * @date 2022/06/27
 * @project whalex-dat-sql
 */
@Slf4j
public class DatPreparedStatement extends DatStatement implements PreparedStatement {

    List<Object[]> paramsList;

    private Object[] params;

    private String[] columnNames;

    private int autoGeneratedKeys;

    private String rowSql;

    public DatPreparedStatement(DatConnection connection, String sql, BaseDbConfTemplate baseDbConfTemplate, DbResourceEnum dbType, DatabaseSetting databaseSetting) {

        super(connection, baseDbConfTemplate, dbType, databaseSetting);

        this.rowSql = sql;

        //确保最后一个字符不是？
        sql = sql + " ";

        String[] split = sql.split("\\?");

        params = new Object[split.length - 1];

        paramsList = new ArrayList<>();
    }

    public DatPreparedStatement(DatConnection connection, String sql, BaseDbConfTemplate baseDbConfTemplate, DbResourceEnum dbType, DatabaseSetting databaseSetting, String[] columnNames) {
        this(connection, sql, baseDbConfTemplate, dbType, databaseSetting);
        this.columnNames = columnNames;
    }

    public DatPreparedStatement(DatConnection connection, String sql, BaseDbConfTemplate baseDbConfTemplate, DbResourceEnum dbType, DatabaseSetting databaseSetting, int autoGeneratedKeys) {
        this(connection, sql, baseDbConfTemplate, dbType, databaseSetting);
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        execute();
        return resultSet;
    }

    @Override
    public int executeUpdate() throws SQLException {
        execute();
        return getUpdateCount();
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        params[parameterIndex - 1] = null;
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setByte(int parameterIndex, byte x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setShort(int parameterIndex, short x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setInt(int parameterIndex, int x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setLong(int parameterIndex, long x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setFloat(int parameterIndex, float x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setDouble(int parameterIndex, double x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setString(int parameterIndex, String x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setDate(int parameterIndex, Date x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setTime(int parameterIndex, Time x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setAsciiStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setUnicodeStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        setBinaryStream(parameterIndex, x, (long) length);
    }

    @Override
    public void clearParameters() throws SQLException {
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        setObject(parameterIndex, x);
    }

    @Override
    public void setObject(int parameterIndex, Object x) throws SQLException {
        if(x  instanceof String) {
            setString(parameterIndex, (String) x);
            return;
        }

        if(x  instanceof Timestamp) {
            setTimestamp(parameterIndex, (Timestamp) x);
            return;
        }

        if(x  instanceof Date) {
            setTimestamp(parameterIndex, new Timestamp(((Date)x).getTime()));
            return;
        }

        if(x instanceof java.util.Date) {
            setTimestamp(parameterIndex, new Timestamp(((java.util.Date)x).getTime()));
            return;
        }
        
        if(x instanceof LocalDateTime) {
            LocalDateTime localDateTime = (LocalDateTime) x;
            ZonedDateTime zonedDateTime = localDateTime.atZone(ZoneId.systemDefault());
            Instant instant = zonedDateTime.toInstant();
            java.util.Date date = java.util.Date.from(instant);
            setTimestamp(parameterIndex, new Timestamp(date.getTime()));
            return;
        }

        if(x instanceof LocalDate) {

            LocalDate localDate = (LocalDate) x;
            LocalDateTime localDateTime = localDate.atStartOfDay();
            ZonedDateTime zonedDateTime = localDateTime.atZone(ZoneId.systemDefault());
            Instant instant = zonedDateTime.toInstant();
            java.util.Date date = java.util.Date.from(instant);
            setTimestamp(parameterIndex, new Timestamp(date.getTime()));
            return;
        }
        

        params[parameterIndex - 1] = x;
    }

    @Override
    public boolean execute() throws SQLException {

        //非批量操作时，resultSet需要设置为空，防止对象复用时，出现数据错误
        if(paramsList.size() == 0) {
            resultSet = null;
        }

        List<Object> paramList = new ArrayList<>();
        if(params.length > 0) {
            paramList.addAll(Arrays.asList(params));
        }

        return execute(rowSql, params, autoGeneratedKeys, columnNames);

    }

    @Override
    public void addBatch() throws SQLException {
        paramsList.add(params);
        params = new Object[params.length];
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setCharacterStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setRef 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setBlob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setClob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setArray(int parameterIndex, Array x) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setArray 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public ResultSetMetaData getMetaData() throws SQLException {

        if(resultSet == null) {
            return null;
        }

        return  resultSet.getMetaData();
    }

    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        setDate(parameterIndex, x);
    }

    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        setTime(parameterIndex, x);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        setTimestamp(parameterIndex, x);
    }

    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        params[parameterIndex - 1] = null;
    }

    @Override
    public void setURL(int parameterIndex, URL x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        return new DatParameterMetaData(params);
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setRowId 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setNString(int parameterIndex, String value) throws SQLException {
        setString(parameterIndex, value);
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
        params[parameterIndex - 1] = value;
    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        params[parameterIndex - 1] = value;
    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setClob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setBlob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setNClob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setSQLXML 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
       setObject(parameterIndex, x);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setAsciiStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        params[parameterIndex - 1] = AniBinaryStreamParameter.builder().inputStream(x).length(length).build();
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setCharacterStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setAsciiStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        params[parameterIndex - 1] = x;
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setCharacterStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setNCharacterStream 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setClob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setBlob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        log.error(this.getClass().getName() + "#" + "setNClob 方法未实现");
        throw new SQLException("方法未实现");
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        throw new SQLException("PreparedStatement不能调用addBatch");
    }

    @Override
    public int[] executeBatch() throws SQLException {
        int[] ints = new int[paramsList.size()];

        for (int i = 0; i < paramsList.size(); i++) {
            params = paramsList.get(i);
            int result = executeUpdate();
            ints[i] = result;
        }
        paramsList.clear();

        return ints;
    }
}
